# Generated by Django 5.0.6 on 2024-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_pasport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierId', models.IntegerField(verbose_name='Id поставщика')),
                ('name', models.TextField(verbose_name='Деталь')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierId', models.IntegerField(verbose_name='Id поставщика')),
                ('Detail', models.IntegerField(verbose_name='Id детали')),
                ('data', models.DateTimeField(verbose_name='Время комментария')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Поставщик')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='RequestId',
        ),
    ]
