# Generated by Django 5.0.6 on 2024-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_detail_order_supplier_delete_job_delete_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField(verbose_name='Id заказа')),
                ('SupplierId', models.IntegerField(verbose_name='Id поставщика')),
                ('DetailId', models.IntegerField(verbose_name='Id детали')),
            ],
            options={
                'verbose_name': 'часть заказа',
                'verbose_name_plural': 'часть заказов',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='Detail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='SupplierId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.AddField(
            model_name='order',
            name='UserId',
            field=models.IntegerField(default=0, verbose_name='Id пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество деталей'),
        ),
    ]
