# Generated by Django 5.0.6 on 2024-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orderitem_remove_order_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='NameOfDetail',
            field=models.TextField(default=0, verbose_name='Имя детали'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='NameOfSupplier',
            field=models.TextField(default=0, verbose_name='Имя поставщика'),
            preserve_default=False,
        ),
    ]
