# Generated by Django 5.0.6 on 2024-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание выполняемыхх работ')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vacancion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
