# Generated by Django 5.0.6 on 2024-05-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_contaсt_contaсts_delete_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaсts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
