# Generated by Django 5.0.6 on 2024-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_isemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IsEmployee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник/Пользователь'),
        ),
    ]
