# Generated by Django 5.0.6 on 2024-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_discount_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
            preserve_default=False,
        ),
    ]
