# Generated by Django 5.0.6 on 2024-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='min_quantity',
            field=models.IntegerField(default=0, verbose_name='Минимальное количество для скидки'),
            preserve_default=False,
        ),
    ]
