# Generated by Django 5.0.6 on 2024-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_discount_min_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(verbose_name='Адрес пункта самовывоза')),
                ('Workinghours', models.TextField(verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Пункт самовывоза',
                'verbose_name_plural': 'Пункты самовывоза',
            },
        ),
    ]
