# Generated by Django 5.0.6 on 2024-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_company_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
