# Generated by Django 5.0.6 on 2024-09-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
    ]
