# Generated by Django 5.0.6 on 2024-09-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='NameOfSupplier',
        ),
    ]
