# Generated by Django 5.0.6 on 2024-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_orderitem_nameofsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='SupplierId',
            field=models.IntegerField(default=0, verbose_name='Id поставщика'),
        ),
    ]
