# Generated by Django 5.0.6 on 2024-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_news_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='FullText',
            field=models.TextField(default='', verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Краткое содержание'),
        ),
    ]
