# Generated by Django 5.0.6 on 2024-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_news_link_news_fulltext_alter_news_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'Истории Компании',
            },
        ),
    ]
